C /etc/drivers/neuron-inf1.toml
C /etc/drivers/neuron-latest.toml
R __PREFIX__/lib/modules/__KERNEL_VERSION__/kernel/drivers/neuron - - - - -
d __PREFIX__/lib/modules/__KERNEL_VERSION__/kernel/drivers/neuron 0755 root root - -
