C /etc/drivers/nvidia-tesla.toml
C /etc/drivers/nvidia-open-gpu.toml
C /etc/drivers/nvidia-open-gpu-copy-only.toml
C /etc/drivers/nvidia-grid.toml
C /etc/drivers/nvidia-grid-copy-only.toml
C /etc/ld.so.conf.d/nvidia-tesla.conf
